export const ActionTypes = {
  SET_POSTS: 'SET_POSTS',
  DELETE_POST: 'DELETE_POST',
  OPEN_MODAL: 'OPEN_MODAL',
  SET_SELECTED_POST: 'SET_SELECTED_POST',
  UPDATE_POST: 'UPDATE_POST',
  CREATE_POST: 'CREATE_POST',
}
